/// Класс содержит в себе Map строк заканчивающихся кодом языка. Служит одновременно для хранения строк текста и локализации приложения.
class AppStrings {
  static const Map<String, String> mapOfStrings = {
    'appNameru': 'Flutter Demo',
    'appNameen': 'Flutter Demo',
    'appTitleru': 'Интересные места',
    'appTitleen': 'Places',
    'appMainDrawnerHeaderru': 'Настройки',
    'appMainDrawnerHeaderen': 'Settings',
    'appMainDrawnerSetting1ru': 'Список мест',
    'appMainDrawnerSetting1en': 'List of interesting places',
    'appMainDrawnerSetting2ru': 'Вторая строка списка',
    'appMainDrawnerSetting2en': 'Settings 2...',
    'appMainDrawnerSetting3ru': 'Третья строка списка',
    'appMainDrawnerSetting3en': 'Settings 3...',
    'appMainColumnFirstElementru': 'Количество нажатий на нопку:',
    'appMainColumnFirstElementen':
        'You have pushed the button this many times:',
    'appMainFirstTextFormFieldhintru': 'Пример строки для ввода',
    'appMainFirstTextFormFieldhinten': 'test hint',
    'appMainFirstTextFormFieldhelperru': 'Введите строку.',
    'appMainFirstTextFormFieldhelperen': 'test helper',
    'appMainFirstTextFormFieldlabelru': 'Нажмите для вызова клавиатуры.',
    'appMainFirstTextFormFieldlabelen': 'test label',
    'appMainNameOfFloatingActionButtonru': 'Увеличение',
    'appMainNameOfFloatingActionButtonen': 'Increment',
    'appSinglePlaceScreenDrawner2ru': 'Основной экран',
    'appSinglePlaceScreenDrawner2en': 'Main screen',
    'appSinglePlaceScreenAppBarTitleru': 'Детальное описание',
    'appSinglePlaceScreenAppBarTitleen': 'description',
    'appSingleListScreenDrawner2ru': 'Выбранные места',
    'appSingleListScreenDrawner2en': 'Selected places',
    'appSingleListScreenAppBarTitleru': 'Список интересных мест',
    'appSingleListScreenAppBarTitleen': 'List of interesting places',
    'appSingleListScreenLikeButtonru': 'Хочу посетить',
    'appSingleListScreenLikeButtonen': 'I want to visit',
    'appSelectedPlacesScreenAppBarTitleru': 'Список выбранных мест',
    'appSelectedPlacesScreenAppBarTitleen': 'List of selected places',
  };
}
